### PR TITLE
Jc/add grid to forms

### PR DESCRIPTION
**Pull request by JCopeland-PIFSC**
Updated multistep form with two improvements:

1. Implemented `useRef` hook to set `ref` for the first input on each step form.
2. Utilized `<GridContainer/> ` and `<Grid/>` components to improve the layout of the forms to provide as a useful example.

Screenshot 2024-03-27 at 2 40 13 PM
Screenshot 2024-03-27 at 2 40 39 PM
Screenshot 2024-03-27 at 2 40 55 PM
Screenshot 2024-03-27 at 2 57 30 PM

### CODE REVIEW

**Comment by JCopeland-PIFSC** [comment]
I am interested in feedback on the `useRef` implementation. My thought was by initializing the refs into an array that the array index could easily be mapped to the current step.

I think it is also worth adding to any documentation related to setting a ref that `@trussworks/react-uswds` exposes a prop named `inputRef`. This could cause confusion is a user assumes they can set a ref by passing a `ref` prop.

**Review by gambinish — APPROVED** [review]
Looks good, but should we maybe write the css in `index.css` rather than including styles inline here?

Just want to avoid having to manage two different ways of creating styles. Open to being convinced otherwise if there's a reason

**Comment by JCopeland-PIFSC** [comment]
The style props that I removed and replace with classNames are using the built in classes provided by USWDS. My thought is that `MultiStepForm.jsx` is an example that would be replaced by a application specific form. In that case we would want to leverage predefined classes when possible and not define new ones. Let me know if I am thinking about this wrong.

**Comment by gambinish** [comment]
> The style props that I removed and replace with classNames are using the built in classes provided by USWDS. My thought is that `MultiStepForm.jsx` is an example that would be replaced by a application specific form. In that case we would want to leverage predefined classes when possible and not define new ones. Let me know if I am thinking about this wrong.

Our initial decision do write plain css was to avoid having the overhead of maintaining both abstracted inline styles (USWDS/bootstrap/tailwind) as well as a custom stylesheet.

I think removing the `style` prop is the right thing to do, but my personal preference would be to replace them with a css class instead of adding in the USWDS class.

**Pull request merged**
